### PR TITLE
Store triggers by job

### PR DESCRIPTION
**Pull request by jsteinich**
Motivation:
We have tens of thousands of jobs which caused major performance issues when the jobs completed. Looking into it further, removing from the triggers list was causing the problem.

Change:
Convert triggers list to a map of lists keyed on JobKey since most accesses are done from the JobKey.

### CODE REVIEW

**Comment by jhouserizer** [comment]
Hi @jsteinich,

This contribution falls under the conditions described under the heading "Contributions which do require a full Contributor’s License Agreement (CLA)" here: http://www.quartz-scheduler.org/community/contribute.html

We very much appreciate your contribution, and request that you submit a signed agreement.

Thanks!

**Comment by jhouserizer** [comment]
Signed CLA received. Thanks!

**Comment by zemian** [comment]
Thanks for the PR @jsteinich ! There is a one extra `{` that resulted in compiler error, but other than that, the change looks good and all tests passed. I will go ahead and fix this minor problem and merge it in.

**Comment by jsteinich** [comment]
Sorry about the error. It must have been a typo when I copied my local change to GitHub.
I'm glad the changes are helpful.

**Pull request merged**
