### PR TITLE
feat: flexible choice of whether to be a task execution node

### PR DESCRIPTION
**Pull request by yuexiamantian**
flexible choice of whether to be a task execution node is supported; in other words, the node can be configured to perform a task or publish only a task

### CODE REVIEW

**Comment by yuexiamantian** [comment]
1.  flexible choice of whether to be a task execution node is supported; in other words, the node can be configured to perform a task or publish only a task
2. Avoid forcing synchronous to asynchronous and transaction management issues in some scenarios

**Comment by akomakom** [comment]
Hello! Thank you very much for your contribution and interest in helping improve the Quartz community.

After a period of dormancy, the Quartz project is back under steady maintenance by multiple volunteers, who are working to once again handle contributions such as yours.

We notice that your contribution was made without use of the DCO feature (the sign-off feature on commits via the -s option). Can you please update your PR with commits that use the -s option, agreeing to assign copyright ownership and other terms as described at the contributor agreement referenced here: https://github.com/quartz-scheduler/contributing/blob/main/CONTRIBUTING.md

You can easily add signoff to your previous commits by running (on your PR branch):
```shell
git commit --amend --signoff --no-edit 
git push -f
```

Or (for multiple commits):
```shell
# change 5 to the number of commits
git rebase HEAD~5 --signoff
git push -f
````

**Comment by jhouserizer** [comment]
This set of commits seems to have a bunch of code for setting the new property and plumbing it through into the internals, but seems to not have any code checking the property and modifying behavior based upon it.

Also, what is the real difference hoped for in this change, as compared to simply not calling scheduler.start() on the nodes that are to be publishers only?

**Comment by yuexiamantian** [comment]
scheduler.start, if executed, can serve as a node for task management: instances can be registered (and expired instances compensated, etc.).

It is a solution of synchronous loading and asynchronous scheduling: on the premise that the common transaction management of tasks and businesses ensures strong data consistency, the asynchronous scheduling of tasks is realized.

> 2021年8月2日 下午10:07，jhouserizer ***@***.***> 写道：
> 
> This set of commits seems to have a bunch of code for setting the new property and plumbing it through into the internals, but seems to not have any code checking the property and modifying behavior based upon it.
> 
> Also, what is the real difference hoped for in this change, as compared to simply not calling scheduler.start() on the nodes that are to be publishers only?
>

**Pull request closed without merging**
