### PR TITLE
Ignore Eclipse files.

### PR DESCRIPTION
**Pull request by garydgregory**
A PR to add Eclipse files like .project, .classpath, .settings (folder) to git ignore files.

### CODE REVIEW

**Comment by jhouserizer** [comment]
Hi, thank you very much for your interest in contributing to the project!  Please read about submitting contributions here: http://www.quartz-scheduler.org/community/contribute.html  and confirm in a reply comment that you agree to the grant statement under the heading "Agreement and Grant of Copyright"

**Comment by garydgregory** [comment]
I emailed my CLA to tc-oss@softwareag.com.

**Comment by jhouserizer** [comment]
Signed CLA received. Thanks!

**Comment by zemian** [comment]
@garydgregory, We have actually merged in a .gitignore at the root of the project already. It should take care of ignoring Eclipse files at any directory level without the need of creating multiple .gitignore. Let us know if that does not work for you.

**Comment by garydgregory** [comment]
Hi @zemian

Nope, that's not a good one. Please see my latest commit on this branch for the proper way to ignore Eclipse files in a root-level .gitIgnore.

Thank you,
Gary

PS: I DocuSigned a CLA this morning. Your legal dept. should have it.

**Comment by jhouserizer** [comment]
Signed CLA received

**Comment by zemian** [comment]
Hi @garydgregory,

I have tested the master branch with eclipse generated project files and git ignore them all in any directories level. What's the reason not working for you?

Here is output when I loaded quartz project using Eclipse Neon and then output of git status. It's all clean:
```
zedeng@mydell ~/ossdev/zemian/quartz-pr12-test
$ find . -name '.project' -o -name '.settings'
./.project
./.settings
./checkstyle/.project
./checkstyle/.settings
./distribution/.project
./distribution/.settings
./distribution/examples/.project
./distribution/examples/.settings
./management-quartz/.settings
./management-quartz-impl/.settings
./quartz/.project
./quartz/.settings
./quartz-commonj/.project
./quartz-commonj/.settings
./quartz-core/.project
./quartz-core/.settings
./quartz-jboss/.project
./quartz-jboss/.settings
./quartz-jobs/.project
./quartz-jobs/.settings
./quartz-oracle/.project
./quartz-oracle/.settings
./quartz-plugins/.project
./quartz-plugins/.settings
./quartz-stubs/.project
./quartz-stubs/.settings
./quartz-weblogic/.project
./quartz-weblogic/.settings
./system-tests/.project
./system-tests/.settings
./terracotta/.project
./terracotta/.settings
./terracotta/bootstrap/.project
./terracotta/bootstrap/.settings

zedeng@mydell ~/ossdev/zemian/quartz-pr12-test
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```

**Comment by zemian** [comment]
The ignore file is working as expected. Closing this PR.

**Pull request closed without merging**
