### PR TITLE
Handle exceptions thrown while retrieving the misfired triggers

### LINKED ISSUE #1152: MisfireHandler cannot recover any triggers if one misfired trigger has errors
This is similar to #48.

In JobStoreSupport.java, `recoverMisfiredJobs` method has a loop:

```
        for (TriggerKey triggerKey: misfiredTriggers) {
            
            OperableTrigger trig = 
                retrieveTrigger(conn, triggerKey);

            if (trig == null) {
                continue;
            }

            doUpdateOfMisfiredTrigger(conn, trig, false, STATE_WAITING, recovering);

            if(trig.getNextFireTime() != null && trig.getNextFireTime().getTime() < earliestNewTime)
                earliestNewTime = trig.getNextFireTime().getTime();
        }
```

It calls `retrieveTrigger` and might throw an exception due to an invalid cron expression, for example.

Then, the entire transaction will be rolled back as there is no error/exception handling in the loop.

It will result in a defunct misfire recovery. It will run into an infinite state that tries to recover the same misfired triggers without success. All other valid triggers will not be recovered and will be stuck forever.

Questions:
1. Is this a known issue and by design?
2. If so, could you please share the background and the reason behind the decision?
3. Can we handle the `retrieveTrigger` exception in the loop and unblock the other valid triggers by skipping the erroneous ones?

Thank you!

### PR DESCRIPTION
**Pull request by ohksj77**
This PR...

Fix #1152

## Changes
- handled exceptions thrown while retrieving the misfired triggers
  - try-catch and logs refer to [quartznet/quartznet#1040](https://github.com/quartznet/quartznet/pull/1040/files) for consistency

-----------------
## Checklist
- [x] tested locally
- [ ] updated the docs
- [ ] added appropriate test
- [x] signed-off on the DCO referenced in the CONTRIBUTING link below via `git commit -s` on my commits, and submit this code under terms of the Apache 2.0 license and assign copyright to the Quartz project owners
  (If you're not using command-line, you can use a [browser extension](https://github.com/scottrigby/dco-gh-ui) )
-----------------
In submitting this contribution, I agree to the terms of contributing as referred to here: 
https://github.com/quartz-scheduler/contributing/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
If you change your comment from `Fixes issue #1152` to `Fix #1152` it will link this PR to the ticket.

**Comment by ohksj77** [comment]
> Can you also make another PR for the 2.4 branch of this fix?

Okay, I'll make a PR for the 2.4 branch too.

**Comment by melloware** [comment]
@ohksj77 this looks great!  do you mind checking this ticket and see if your fixes fix this issue: https://github.com/quartz-scheduler/quartz/issues/1245

**Comment by ohksj77** [comment]
@melloware My fix doesn't seem to affect the issue.
I tried running both the version I fixed and the previous version, following the reproduction steps, and found the same results in both cases.

**Comment by melloware** [comment]
Ok thanks for checking!

**Review by jhouserizer — APPROVED** [review]
Thanks. This is an improvement.  But there is still some strange/undefined ambiguity around what does and what should happen to triggers that fail to load during misfire handling ... someday somebody needs to think more about that. :)

**Pull request merged**
