### PR TITLE
Update c3p0 to version 0.9.5.4

### PR DESCRIPTION
**Pull request by chrisdennis**

### CODE REVIEW

**Comment by chrisdennis** [comment]
I believe this falls under "contributions which do no require a full Contributor's License Agreement", as described here: http://www.quartz-scheduler.org/community/contribute.html#contributions-which-do-not-require-full-contributors-license-agreement-cla

@J3173 If you could confirm that you agree with a simple yes below that would be great!

**Comment by melloware** [comment]
@chrisdennis if @J3173 does not respond I can also submit this PR and then respond with an approval if it helps?    Also if this project is looking for committers I am an active GitHub committer and have Maven Central permissions.   Just throwing that out there...

**Comment by J3173** [comment]
> I believe this falls under "contributions which do no require a full Contributor's License Agreement", as described here: http://www.quartz-scheduler.org/community/contribute.html#contributions-which-do-not-require-full-contributors-license-agreement-cla
> 
> @J3173 If you could confirm that you agree with a simple yes below that would be great!

Yes, I agree.

**Comment by chrisdennis** [comment]
> Also if this project is looking for committers I am an active GitHub committer and have Maven Central permissions. Just throwing that out there...

@melloware Right now @jhouserizer and I are just trying to get back on top of the open issues/PRs with a focus on getting bugs fixed and merged. There is discussion going on internally regarding the future, but it's all just discussion for now. When that discussion approaches some kind of conclusion we can/should talk.

**Comment by melloware** [comment]
No problem.  thanks for your response!

**Pull request merged**
