### PR TITLE
correct a few occurrences of "the the"

### PR DESCRIPTION
**Pull request by carehart**

### CODE REVIEW

**Comment by akomakom** [comment]
Hello! Thank you very much for your contribution and interest in helping improve the Quartz community.

After a period of dormancy, the Quartz project is back under steady maintenance by multiple volunteers, who are working to once again handle contributions such as yours.

We notice that your contribution was made without use of the DCO feature (the sign-off feature on commits via the -s option). Can you please update your PR with commits that use the -s option, agreeing to assign copyright ownership and other terms as described at the contributor agreement referenced here: https://github.com/quartz-scheduler/contributing/blob/main/CONTRIBUTING.md

You can easily add signoff to your previous commits by running (on your PR branch):
```shell
git commit --amend --signoff --no-edit 
git push -f
```

Or (for multiple commits):
```shell
# change 5 to the number of commits
git rebase HEAD~5 --signoff
git push -f
````

**Comment by carehart** [comment]
OK, done. (Since I edited the doc through the github web ui, it was not quite as simple as the steps you offered, but I hope I got it right.)

**Comment by akomakom** [comment]
@carehart Thanks!  I didn't even think of the browser use case.

**Comment by carehart** [comment]
Thanks, and you're not at all alone. Many of us who focus on offering updates to docs may make and commit such changes entirely in the browser, and yet nearly always if we forget about the DCO, the steps offered by project owners (or bots) propose those steps.. 

The good news is that there is a browser extension called [DCO signoff for GitHub UI](https://chrome.google.com/webstore/detail/dco-github-ui/onhgmjhnaeipfgacbglaphlmllkpoijo?hl=en) (itself open source and [available in github](https://github.com/scottrigby/dco-gh-ui)) that can handle putting in the DCO for us, when we make a PR.  I just must not have had that in place on the browser when I had made that PR some months ago.

Hope that may help someone else. Great to hear the renewed focus on the project/repo.

**Comment by akomakom** [comment]
Thanks @carehart, that is useful.

**Pull request merged**
