### PR TITLE
Implemented Paused in CompletedInstruction

### PR DESCRIPTION
**Pull request by ramaraochavali**

### CODE REVIEW

**Comment by zemian** [comment]
Hi @ramaraochavali 

Thank you for the contribution to Quartz! Sorry for the long delay in responding to this PR!

This is a feature request. The workaround is user can simply write a JobListener and perform the pause there. Adding new entries into CompletedExecutionInstruction seem to be complicated. But since you have already implemented, we would like to consider it.

BTW, Your changes require a Contribution License Agreement (CLA) to be submitted. 
You can find the instructions in http://www.quartz-scheduler.org/community/contribute.html

Can you please submit the CLA so we can consider merging in your changes?

**Comment by zemian** [comment]
Close due to inactivities

**Comment by ramaraochavali** [comment]
@zemian I have already submitted CLA earlier as one of my previous PRs got merged. Do you want another CLA to be submitted?

**Comment by zemian** [comment]
Oh, I didn't know that. I will have to verify CLA and review it again. But as I mentioned in the comment, I still don't think the feature is worth the complexity since user has work around. I will leave it open and see if any other use will vote for this, if not. I don't think we want to maintain it.

**Comment by ramaraochavali** [comment]
Fair enough. Please feel free to close if there are no votes

**Comment by chrisdennis** [comment]
I'm going to close this... but @ramaraochavali if you want to campaign for it's reintroduction then don't be discouraged, I'm just following through on the process Zemian started - if you want to re-open and make a case then go ahead.

**Pull request closed without merging**
