### PR TITLE
TAB-4700 : Remove update-checker feature

### PR DESCRIPTION
**Pull request by rishabhmonga**

### CODE REVIEW

**Comment by jhouserizer** [comment]
Looks good!  Thanks.

**Comment by chrisdennis** [comment]
There are a lot of changes to unrelated lines in the examples properties files.  I think there all just the removal of commented lines, but the timing seems weird. Was this intentional?

**Comment by rishabhmonga** [comment]
Had received a comment from Louis on the CR I had created earlier, suggesting that we could loose the commented lines in the properties files

**Comment by chrisdennis** [comment]
Cool - thanks for following up.

**Comment by ljacomet** [comment]
that's interesting :wink:

My other comment was mostly to not add commented lines about the update check since it is completely removed. I did not look at the context and did not realise there were already commented lines.

But hey, @jhouserizer found it fine!

**Pull request merged**
