### PR TITLE
Move database schema scripts to quartz-core

### LINKED ISSUE #4: Include DB schema scripts in org.quartz-scheduler:quartz artifact
It would be much more convenient for the users if DB schema scripts were included in ```org.quartz-scheduler:quartz``` artifact rather than having to download the distribution archive and extract them from there.

This way the scripts would easily obtainable using the dependency management system of choice. In addition, this would also allow for a programmatic access to scripts since they would automatically be included in the classpath.

Many other popular frameworks take this approach, for example many Spring projects (Integration, Batch, Security...), Activiti BPMN, etc.

### PR DESCRIPTION
**Pull request by vpavic**
This resolves #4.

With scripts now being present on the classpath, `JdbcQuartzTestUtilities` and `JdbcQuartzDerbyUtilities` have been updated to use `tables_derby.sql` from the new location.

~~The PR also includes commit that adds `.gitignore` to the project.~~

Together with this change, [Tutorial on Job Stores](http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/tutorial-lesson-09.html) should be updated to refer to the new location of the schema scripts.

### CODE REVIEW

**Comment by jhouserizer** [comment]
Hi @vpavic,

This contribution falls under the conditions described under the heading "Contributions which do require a full Contributor’s License Agreement (CLA)" here: http://www.quartz-scheduler.org/community/contribute.html

We very much appreciate your contribution, and request that you submit a signed agreement.

Thanks!

**Comment by vpavic** [comment]
Hi @jhouserizer - thanks for the feedback.

I don't have a printer/scanner at hand ATM since I'm on a business trip but I'll send you the signed CLA as soon I'm able to (probably within a day or two).

In the meanwhile I've updated the PR to resolve the conflicts.

**Comment by vpavic** [comment]
@jhouserizer I've emailed the signed CLA.

**Comment by jhouserizer** [comment]
CLA received.  Thank you.

**Comment by zemian** [comment]
Hi @vpavic , I didn't see this PR before I merged another PR that touched the tables_mysql.sql and tables_mysql_innodb.sql. Can you please get latest and resolve these conflict one more time? I can review and merge your PR next.

@jhouserizer do you know where we should update the text in Tutorial link mentioned above?

**Comment by vpavic** [comment]
Hi @zemian - I've updated the PR, please review. Thanks.

BTW, is there any ETA for the release that will contain these changes?

**Comment by zemian** [comment]
Thanks @vpavic ! I think this PR would consider as new feature rather than bugfix though. Our current master is at 2.2.4-SNAPSHOT bugfix mode. I am thinking to prepare a new branch for current 2.2.x bug fixes, and then merge your PR into master to starting the new 2.3.x work. If this is the case then you can expect these to be in 2.3.0 release, which I don't have a date yet.

**Comment by vpavic** [comment]
Thanks for merging this! :+1:

I agree it's a new feature and therefore more suitable for the 2.3.

Regarding release plans/schedule, it would be nice if [the milestones page](https://github.com/quartz-scheduler/quartz/milestones) would be updated once you have some concrete dates. Assigning individual issues/PRs to milestones would be helpful as well.

**Comment by zemian** [comment]
Doc is updated with quartz-scheduler/quartz-scheduler.org-site#12

**Comment by ptahchiev** [comment]
Hey guys, when can we expect 2.3?

**Pull request merged**
