### PR TITLE
Add support for HikariCP connection pool

### PR DESCRIPTION
**Pull request by lorban**

### CODE REVIEW

**Comment by zemian** [comment]
Hi @lorban ,

I have looked into your PR and besides fixing the conflict, I have few concerns.

1) I am not sure introducing provider predefined names (using c3p0 or hikari) config property is a clean way to do this. We already have .class to provide a implementation, so it makes more sense just to let this classname value to drive the rest of config bean set. Why need another short name?

2) It seems that the old PoolingConnectionProvider (old c3p0) iml actually initialized the underneath DataSource in the constructor, and then leave the actual initialize() method empty. I think these should be reversed, and provide a empty constructor so that we can load the provider same way as as any custom provider.

3) Some one mentioned in an Issue #19 that we have hard (compile) dependency on c3p0 with quartz, so I am hoping this PR change can also remove that. We can continue to package a CP package jar if we need to, but the maven pom dependencies on "quartz" should not contains it for client. Just like a SLF4J, they have to pick an implementation for their need.

**Comment by zemian** [comment]
Hi @lorban ,

I have looked into this PR and have few concerns (besides the file conflicts)

1) Adding new provider short name (eg: "c3p0" or "hiraki") is unnecessary and might be confusing to users. We already have the "connectionProvider.class." property, and this along should be unique and able to drive what's needed for rest of the bean properties.

2) The existing PoolingConnectionProvider (c3p0 impl) actually invoke initialization code in the constructor, and then leave the ConnectionProvider interface's "initialize()" method empty. This should really be reversed. We should provide a default empty constructor for c3p0 and use "initialize" properly. I would like to see our own provider impl should work load and work just like any other custom provider.

3) In Issue#19 someone points out we have a hard (compile) c3p0 maven dependency with quartz. I was hoping this PR can also address that. Would it make sense to not couple this dependency?

**Comment by amilarajans** [comment]
+1

**Comment by jhouserizer** [comment]
see #126 , which replaces this PR.  Thanks, @lorban .

**Pull request closed without merging**
