### PR TITLE
Fix #1161 Add Oracle23 SQL script using BOOLEAN

### LINKED ISSUE #1161: [Oracle 23] VARCHAR2(1) breaking change
**Current behavior**

Job can no more be registered inside job detail table.

```
Caused by: org.quartz.JobPersistenceException: Couldn't store job: ORA-12899: valeur trop grande pour la colonne "QUARKUS"."QRTZ_JOB_DETAILS"."IS_DURABLE" (réelle : 5, maximum : 1)
```

**Expected behavior**

Job should be stored and next executed as expected.

**Additional information**

Oracle 23 has introduced a breaking change regarding the way a boolean is represented.
Before Oracle 23 a boolean used a **VARCHAR2(1)** and this way has been supported from many years by the oracle jdbc driver.

Now, Oracle 23 has introduced a new type **BOOLEAN** to represent a boolean type.
But, the driver is no more compatible - except if an additional property is used to deactivate the new way to handle boolean type.

Full story here with a reproducer : https://github.com/quarkusio/quarkus/issues/43720

**How to fix**

Provide an update script for Oracle database 23 and plus to update boolean columns **VARCHAR2(1)** to **BOOLEAN**
or
provide a new full initialization tables for Oracle database 23 and plus.

Multiples tables are impacted.

Regards,
Damien

### PR DESCRIPTION
**Pull request by melloware**
Fix #1161 Add Oracle23 SQL script using BOOLEAN

Oracle 23 uses BOOLEAN instead of VARCHAR2(1)

### CODE REVIEW

**Comment by bcode2** [comment]
Should we worry about this?

`
    /**
     * Retrieves the value of the designated column in the current row
     * of this <code>ResultSet</code> object as
     * a <code>boolean</code> in the Java programming language.
     *
     * <P>If the designated column has a datatype of CHAR or VARCHAR
     * and contains a "0" or has a datatype of BIT, TINYINT, SMALLINT, INTEGER or BIGINT
     * and contains  a 0, a value of <code>false</code> is returned.  If the designated column has a datatype
     * of CHAR or VARCHAR
     * and contains a "1" or has a datatype of BIT, TINYINT, SMALLINT, INTEGER or BIGINT
     * and contains  a 1, a value of <code>true</code> is returned.
     *
     * @param columnLabel the label for the column specified with the SQL AS clause.  If the SQL AS clause was not specified, then the label is the name of the column
     * @return the column value; if the value is SQL <code>NULL</code>, the
     * value returned is <code>false</code>
     * @exception SQLException if the columnLabel is not valid;
     * if a database access error occurs or this method is
     *            called on a closed result set
     */
    boolean getBoolean(String columnLabel) throws SQLException;`

**Comment by melloware** [comment]
Good question.  We have this discussion going on https://github.com/quarkusio/quarkus/issues/43720#issuecomment-2399045448

And I have been running fine with these changes as well so i think its all working

**Comment by bcode2** [comment]
Perfect!!!!!! @melloware  :+1:

**Review by jhouserizer — APPROVED** [review]

**Comment by jhouserizer** [comment]
Thanks!

**Pull request merged**
