### PR TITLE
Issue #467 provide XML parser with a strong configuration to prevent …

### PR DESCRIPTION
**Pull request by jgallimore**
…XXE attacks.

This includes a unit test with the sample payload provided on the issue. This uses the OWASP configuration guidelines for Xerces from https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html.

### CODE REVIEW

**Comment by davidmoten** [comment]
You have two PRs submitted on this issue, can you clean up?

**Comment by jgallimore** [comment]
Hi @davidmoten ,

The two PRs are for two different branches - this one is for 2.2.x, and #472 is for master, so I'm not sure cleanup is required, unless the community is specifically stating that they do not want the change backported to maintenance branches.

I'm not sure why I didn't create them for 2.3.x and 3.0.x at the time, but I'd be happy to backport this change to those branches too (and any others) - that would mean another couple of PRs.

I personally use Quartz 2.2.x, so would like to see a release on that branch, but I'll understand if the community does not want to release that, and I'm happy to help in any way I can in any case.

**Comment by jgallimore** [comment]
Sorry, my bad, I did do a PR for 2.3.x - that's #481 - so there are 3 PRs in total. #472 is for master, and the other 2 backport the change to older branches. Thanks for the reviews.

**Comment by chrisdennis** [comment]
Replaced by the daggy PR #503

**Pull request closed without merging**
