### PR TITLE
Fix GroupMatcher.anyXXXGroup() javadoc

### PR DESCRIPTION
**Pull request by Zardoz89**
Fix copy&paste wrong javadoc for anyXXXGroup()

### CODE REVIEW

**Comment by akomakom** [comment]
Hello! Thank you very much for your contribution and interest in helping improve the Quartz community.

After a period of dormancy, the Quartz project is back under steady maintenance by multiple volunteers, who are working to once again handle contributions such as yours.

We notice that your contribution was made without use of the DCO feature (the sign-off feature on commits via the -s option). Can you please update your PR with commits that use the -s option, agreeing to assign copyright ownership and other terms as described at the contributor agreement referenced here: https://github.com/quartz-scheduler/contributing/blob/main/CONTRIBUTING.md

You can easily add signoff to your previous commits by running (on your PR branch):
```shell
git commit --amend --signoff --no-edit 
git push -f
```

Or (for multiple commits):
```shell
# change 5 to the number of commits
git rebase HEAD~5 --signoff
git push -f
````

**Comment by Zardoz89** [comment]
I could be a bit problematic. I think that I don't have any local fork/repository, and I did all on the github web interface.

**Comment by akomakom** [comment]
@Zardoz89 FYI You can use a [browser extension](https://github.com/scottrigby/dco-gh-ui) if you're not using command-line.  This is a convenience, you could add the `Signed-off-by` string to your commit message manually as well.

**Comment by Zardoz89** [comment]
I see, but... How I can actually "edit" my commit from 2019 that only lives on GitHub PR ?

**Comment by akomakom** [comment]
I'm not aware of an option to amend a commit using the GitHub UI alone.

If you don't want to use command-line, there is this: https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/amending-a-commit

You can also close your PR, and open a new one using the same steps as you did in 2019 (plus the signoff).

**Pull request closed without merging**
