### PR TITLE
Fixed the jobs recovering (on scheduler startup) blocks simple trigger after failover situation for job which was executing during JVM crash

### PR DESCRIPTION
**Pull request by eugene-goroschenya**
Fix for #93

### CODE REVIEW

**Comment by jhouserizer** [comment]
Hi @eugene-goroschenya ,

This contribution falls under the conditions described under the heading "Contributions which do require a full Contributor’s License Agreement (CLA)" here: http://www.quartz-scheduler.org/community/contribute.html

We very much appreciate your contribution, and request that you submit a signed agreement.

Thanks!

**Comment by eugene-goroschenya** [comment]
CLA was provided to contributors@terracotta.org

See email sent by Hannelore Schubert (Hannelore.Schubert@opuscapita.com) on 11.01.2017, subject - Open Source Software Library "Quartz".

**Comment by zemian** [comment]
Oh wow, this is bad bug, and thanks a lot @eugene-goroschenya for the fix!

My only minor comment is that in RecoverJobsTest line 84, I would suggest we should close the DB connection that used after DB check. Closing just Statement is not clean enough.

Also since RecoverJobsTestJob is only used in RecoverJobsTest, I would suggest we create a inner class in RecoverJobsTest instead of under the full package.

@jhouserizer is the CLA all good and can we merge once it's ready?

**Comment by jhouserizer** [comment]
Obviously we'll want this in trunk also.

**Comment by zemian** [comment]
I have some free time now, so I will help merge this in and port to trunk.

**Comment by egoroschenya-sc** [comment]
Hi @jhouserizer and @zemian

Thanks for reviewing and merging PR quite fast.
 
Any plans to release quartz-2.2.4 bugfix version?

We are looking forward the official quartz version where this bug has been fixed.

**Comment by jofranke** [comment]
Dear @jhouserizer and @zemian,
is an offical quartz quartz-2.2.4 release containing the fix of this issue scheduled?
The bug causes problems in our software and we need plan our strategy of solving them.

**Pull request merged**
