### PR TITLE
use varbinary(max) instead of image data-type - Fixes #157

### LINKED ISSUE #157: Update to tables_sqlServer.sql - IMAGE data type
It was brought to my attention that future version of sqlserver will be dropping support for the 'IMAGE' datatype

https://docs.microsoft.com/en-us/sql/t-sql/data-types/ntext-text-and-image-transact-sql

"ntext, text, and image data types will be removed in a future version of SQL Server. Avoid using these data types in new development work, and plan to modify applications that currently use them. Use nvarchar(max), varchar(max), and varbinary(max) instead"

Are there any plans to update the sql script and replace the 'IMAGE' datatype?

### PR DESCRIPTION
**Pull request by efwe**
As discussed before this is the minimal approach.

### CODE REVIEW

**Comment by efwe** [comment]
Hello there,
is there anything I can do better? What do you think about this minimal approach?
Keep up the good work,
~fw

**Comment by akomakom** [comment]
Hello! Thank you very much for your contribution and interest in helping improve the Quartz community.

After a period of dormancy, the Quartz project is back under steady maintenance by multiple volunteers, who are working to once again handle contributions such as yours.

We notice that your contribution was made without use of the DCO feature (the sign-off feature on commits via the -s option). Can you please update your PR with commits that use the -s option, agreeing to assign copyright ownership and other terms as described at the contributor agreement referenced here: https://github.com/quartz-scheduler/contributing/blob/main/CONTRIBUTING.md

You can easily add signoff to your previous commits by running (on your PR branch):
```shell
git commit --amend --signoff --no-edit 
git push -f
```

Or (for multiple commits):
```shell
# change 5 to the number of commits
git rebase HEAD~5 --signoff
git push -f
````

**Comment by efwe** [comment]
Hello @akomakom ,

I signed-off my commit.

Good to see the project back from hibernation :)

~fw

**Comment by jhouserizer** [comment]
Thanks!

**Pull request merged**
