### PR TITLE
Add support for ppc64le

### PR DESCRIPTION
**Pull request by akhileshbhople**
I have added support for ppc64le in travis.yml file. Please review.

Thanks!

### CODE REVIEW

**Comment by akhileshbhople** [comment]
The pull check on Azure Pipeline is failing with following error : 

2018-10-26T04:10:39.9766773Z Downloading from central: https://repo.maven.apache.org/maven2/jboss/jboss-common/4.0.2/jboss-common-4.0.2.pom
2018-10-26T05:00:35.1495370Z ##[error]The operation was canceled.
2018-10-26T05:00:35.1511892Z ##[section]Finishing: Maven

This looks like an issue on azure end where the build is getting stalled.

Travis changes are working as expected.

**Comment by jarlah** [comment]
considering why i should include this in my fork. why should we add linux **and** linux-ppc64le? Is linux build standard for travis and must the default be added when you override build os?

**Comment by akhileshbhople** [comment]
@jarlah travis-ci will by default run all its builds on linux (arch x86). Specifying multiple values of OS in the travis.yml allows you to execute the builds on multiple OS simultaneously. However, if we do not specify the default value in the OS section, it will be overridden by the values in the travis.yml. 

In this case the builds will be run on linux (arch x86) and linux (arch ppc64le i.e IBM Power) as sub jobs of the main build because we have specified both the OS in travis.yml. This will allow you to verify all your changes on ppc64le arch as well.

You can refer this link : https://travis-ci.org/akhileshbhople/quartz 

Please let me know if you have any more queries.

**Comment by jarlah** [comment]
Added it to my clone project travis config.

There is not going to be done anything in this project. I have asked the devs about it.

**Comment by zemian** [comment]
Hi @akhileshbhople Thanks for submitting PR. 

1. Couple of updates. First, we no longer using Travis as CI for quartz. 
2. I do not see the benefits of adding a CI build with just in PPC64 machine. The quartz is Java based, and we do not use anything native specifically. This only verify the VM on that host more than anything else.

We plan to close this PR if no further updates soon.

**Comment by zemian** [comment]
Close as invalid

**Pull request closed without merging**
