### PR TITLE
Support job services in OSGi framework with JobStoreTX and JobStoreCMT

### PR DESCRIPTION
**Pull request by SinaTadayon**
```
Motivation:
    Lack of support job services in OSGi framework when job store set to JobStoreTX/JobStoreCMT

Modifications:
    Create org.quartz.osgi package that contains follow features:
        - Initialize Quartz bundle with Activator
        - Tracking register/unregister of job services
        - Provide ClassLoaderHelper that can load classes of 
          job services from other bundles

    Modify org.quartz.simpl.CascadingClassLoadHelper.java:
        - Add BundleClassLoaderHelper to end of loaders list

    Modify quartz-core/pom.xml:
        - Add Bundle-Activator tag
        - Modify Private-Package

    Add .gitignore file that to ignore IDE files and etc.

Result:
    The Quartz support job schedule when OSGi job services configured with 
    JobStoreTX/JobStoreCMT
```

### CODE REVIEW

**Comment by zemian** [comment]
Hi all, I don't have enough knowledge to test this PR in OSGI env from my machine. Can someone from the quartz dev group help verify this PR?

Also, please remove .gitignore as part of the PR because we already have the correct one set in master now.

Also please ensure same valid changes is apply to quartz-2.2.x branch.

Thanks!

**Comment by SinaTadayon** [comment]
hi Zemian
you test this PR to the Karaf container which first create the Quartz bundle then install it. 
you can writing a job service and register it into OSGI framework which the quartz tracking your service then scheduled and execute it.
 
I test it this project with  quartz-2.2.x  into my project and it's work.

I will remove .gitignore file

**Comment by jhouserizer** [comment]
Hi @SinaTadayon ,

This contribution falls under the conditions described under the heading "Contributions which do require a full Contributor’s License Agreement (CLA)" here: http://www.quartz-scheduler.org/community/contribute.html

We very much appreciate your contribution, and request that you submit a signed agreement.

**Comment by jhouserizer** [comment]
Without CLA in the next day or two, this PR will have to be removed from the 2.3.0 milestone

**Comment by SinaTadayon** [comment]
Dear jhouserizer
Excuse me for delay to answer
I read the contribution agreement and i agree it.
I attached it.

Beat Regards

S.T
​
 Terracota Contribution_20170406200226748.pdf
<https://drive.google.com/file/d/0B5s4Dzg2PgcSMkwteEFLVDRpeURCY0VhZGFNdXZxUURfbF84/view?usp=drive_web>
​

**Comment by jhouserizer** [comment]
Thank you.  Could you also either: 1) update the PR wil the .gitignore file removed, or 2) give me permission to commit/push to your branch.

**Comment by SinaTadayon** [comment]
I solved the conflict.
Please check it.

thx

**Comment by jhouserizer** [comment]
Thanks, I will try to review soon.   Also, I haven't been able to access that file in your google drive - I sent a couple requests for access - please note them in your google inbox.

**Comment by SinaTadayon** [comment]
Excuse me,
i send it.
Please check it.

Thanks

**Comment by jhouserizer** [comment]
I'm not sure we want the changes to CascadingClassLoadHelper that are currently included in this PR.  I believe it will make all quartz users dependent upon the osgi libraries.

Perhaps an improvement would be to create a new ClassLoadHelper for use by those who are actually using osgi.

**Comment by SinaTadayon** [comment]
The OSGI libraries are arbitrary which does not forced quartz users dependent to the osgi.
The quartz architecture forced a new ClassLoadHelper must be add to the CascadingClassLoadHelper which it work probably.
I created a new BundleClassLoadHelper which it implement ClassLoadHelper, but to add the BundleClassLoadHelper to the quartz , i found the CascadingClassLoadHelper and modify it.
please help me and tell me where is to add the BundleClassLoadHelper to the quartz.

Thx

**Comment by jhouserizer** [comment]
I will go ahead and merge this, then refactor it some so that the core CascadingClassLoadHelper is not altered, and osgi users can specify a specific class load helper with the existing configuration property "org.quartz.scheduler.classLoadHelper.class".

**Comment by jhouserizer** [comment]
Thank you.

**Comment by SinaTadayon** [comment]
Thank you and Best Regards

**Pull request merged**
