### PR TITLE
Fix for "Cannot create tables in MySQL with InnoDB and UTF8mb4"

### PR DESCRIPTION
**Pull request by krrg**
See https://github.com/quartz-scheduler/quartz/issues/6

### CODE REVIEW

**Comment by disaacson** [comment]
I wouldn't mind if these fields were even smaller. 380 total characters for an identifier is pretty large. Should we reduce the size to 100 chars wide?

**Comment by krrg** [comment]
I can't imagine a situation in which a 190 character identifier would be needed or would be valuable.

**Comment by jhouserizer** [comment]
Hi, thank you very much for your interest in contributing to the project!  Please read about submitting contributions here: http://www.quartz-scheduler.org/community/contribute.html  and confirm in a reply comment that you agree to the grant statement under the heading "Agreement and Grant of Copyright"

**Comment by poojits** [comment]
`CALENDAR_NAME` should also be changed to`VARCHAR(190)` in `QRTZ_CALENDARS` and `QRTZ_CALENDARS` as there are indices on `CALENDAR_NAME` as well. Also, one should also modify `tables_mysql_innodb.sql` as well.

**Comment by zemian** [comment]
Thanks for the PR @krrg 
Since these are InnoDB specific, can you modify your PR to tables_mysql_innodb.sql file instead? We can leave the original tables_mysql.sql if that does not bother anyone. Also can you please also update the ones mentioned by @poojits ?

**Comment by krrg** [comment]
@jhouserizer  I agree to the grant statement. 

I'll go ahead and implement the changes listed by @poojits and move the changes into the `tables_mysql_innodb.sql` and update the PR as soon as I have a spare cycle (should be today).

**Comment by zemian** [comment]
Looks good @krrg Thanks for the contribution!

**Pull request merged**
