### PR TITLE
Implement CronExpression.getTimeBefore() method

### PR DESCRIPTION
**Pull request by amichair**
In submitting this contribution, I agree to the current Software AG contributor agreement as referred to here: 
https://github.com/quartz-scheduler/contributing/blob/main/CONTRIBUTING.md

This PR...
## Changes
- Implements the CronExpression.getTimeBefore() method

## Checklist
- [ ] tested locally
- [ ] updated the docs
- [x] added appropriate test
- [x] signed-off on the above mentioned SoftwareAG contributor agreement via `git commit -s` on my commits. 
  (If you're not using command-line, you can use a [browser extension](https://github.com/scottrigby/dco-gh-ui) )

Fixes #

### CODE REVIEW

**Comment by amichair** [comment]
Good question, is there anything I can do to help move it forward? It's a fully working implementation, just waiting to be merged...

**Comment by amichair** [comment]
Please do not mark it as stale until any developer responds, if there are any left...

**Comment by amichair** [comment]
Please reopen this and leave it open until someone responds.

**Comment by amichair** [comment]
Please reopen and apply this.

**Comment by jhouserizer** [comment]
Looks good but PR will need to be re-created - Unfortunately, due to the change of ownership of this project, the terms of contribution have been updated, and this PR will need to be re-created, agreeing to the new terms.

**Comment by amichair** [comment]
Re-created as PR #1350.

**Pull request closed without merging**
