### PR TITLE
Changelog xml for liquibase

### PR DESCRIPTION
**Pull request by nasazh**
Added xml for liquibase integration.

### CODE REVIEW

**Comment by jhouserizer** [comment]
Hi @nasazh ,

This contribution falls under the conditions described under the heading "Contributions which do require a full Contributor’s License Agreement (CLA)" here: http://www.quartz-scheduler.org/community/contribute.html

We very much appreciate your contribution, and request that you submit a signed agreement.

Thanks!

**Comment by jhouserizer** [comment]
This is an interesting contribution that will likely be useful to many users!

**Comment by jhouserizer** [comment]
As for the location of the file, would it make more sense to put it next to the existing db creation scripts? (docs/dbtables folder).

**Comment by nasazh** [comment]
Hello @jhouserizer,

I've sent CLA to contributors@terracotta.org.
For the location of the file - I totally agree with you, but I can't find the location you described, so I'll leave it up to you to move it to the correct location.

**Comment by zemian** [comment]
Hi there @nasazh unfortunately I don't have knowledge to test this XML using liquibase though, but since you signed the CLA, I accepted the PR for now. If you have time, please provide docs on how to use it. Or else we will find better way to verify and usage of it later.

**Pull request merged**
