### PR TITLE
Workflow engine

### PR DESCRIPTION
**Pull request by dpolivaev**
In submitting this contribution, I agree to the current Software AG contributor agreement as referred to here: https://github.com/quartz-scheduler/contributing/blob/main/CONTRIBUTING.md.

For my work at [Unite](https://github.com/quartz-scheduler/contributing/blob/main/CONTRIBUTING.md), I needed a workflow engine capable of running some analyses, gathering and processing data from different servers. The complete analysis consists of multiple jobs, and some jobs can only run after the previous jobs have successfully finished.

To meet this need, I have developed a small library based on Quartz. As I find it very useful and want people to be able to find it easily, I am submitting it as a contribution to the original Quartz project.

# Key Features

* Job workflows: A sequence of jobs, where each job runs after its predecessor has completed.
* Rules: Define the relationship between preceding and following jobs.
* Rules can be defined for single jobs, arbitrary combinations of jobs running in any order or parallel, and for job groups.
* A workflow extension mechanism allows for adding new jobs to an already started workflow.
* Utilities are available to automatically repeat failed jobs.
* A mechanism exists for sending data from finished jobs to following jobs using the job data map.
* Workflow jobs can run across different schedulers having different thread priorities and thread counts.
* Callback jobs to notify servers when any workflow jobs finish.

# Tests

All the features have been thoroughly tested, with good test coverage. 

# Documentation

Currently, I have only contributed example 16 to the example subproject, which covers only a small part of the functionality. You can find further examples in the tests. If you express general interest in accepting the submission, I am willing to add javadoc for the API and write tutorials in Markdown or Autodoc that match your current standards.

# License and Copyright Considerations

If you confirm your interest in accepting the PR and if the transfer of copyrights is necessary for the contribution to be accepted, I will request confirmation from my company's management. Please note that I am willing to transfer the copyrights only if it is necessary for the contribution to be accepted. As an open source enthusiast, I believe in contributing to the community and making it easier for others to benefit from my work. I hope we can work together to make this contribution a success.

### CODE REVIEW

**Comment by dpolivaev** [comment]
I would appreciate any feedback from the maintainer

**Comment by aadrian** [comment]
@dpolivaev 
Is the "Workflow" a DAG, and can it be rendered visually? e.g. like https://github.com/dagu-dev/dagu#web-user-interface does ?

Thank you.

**Comment by dpolivaev** [comment]
With the "Workflow," you can define rules saying which jobs or job groups should run after some jobs or job groups finish.
It is useful if the results of some jobs are required in follow-up jobs.
Visualization and UI are not in the scope of this pull request.

**Comment by jhouserizer** [comment]
Unfortunately, due to the change of ownership of this project, the terms of contribution have been updated, and this PR will need to be re-created, agreeing to the new terms.

(The above is comment and closing of all open PRs is being done in mass.   This contribution is significant in size/scope so you way want to consider project discussion before putting in more effort.)

**Pull request closed without merging**
