### PR TITLE
Quartz 2.4.x refactor 2024-10-17_01

### PR DESCRIPTION
**Pull request by bcode2**
This PR...

Fixes issue #

## Changes
- refactor: set certain fields as final
- refactor: make serialVersionUID field private

-----------------
## Checklist
- [x] tested locally
- [ ] updated the docs
- [ ] added appropriate test
- [x] signed-off on the DCO referenced in the CONTRIBUTING link below via `git commit -s` on my commits, and submit this code under terms of the Apache 2.0 license and assign copyright to the Quartz project owners
  (If you're not using command-line, you can use a [browser extension](https://github.com/scottrigby/dco-gh-ui) )
-----------------
In submitting this contribution, I agree to the terms of contributing as referred to here: 
https://github.com/quartz-scheduler/contributing/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by bcode2** [comment]
Some test are failing , specially those that i run locally :)

**Comment by jhouserizer** [comment]
it works better if you don't run tests.  even better if you don't compile.

**Comment by bcode2** [comment]
the strange thing is that with java11 is OK :)

**Comment by jhouserizer** [comment]
Hmm.  I hit re-run on the job (check) and it passed.  That test has never been unstable before, I'm not sure what to think.  Reviewing the code changes I don't see how it could lead to the test failing.

**Review by jhouserizer — APPROVED** [review]

**Pull request merged**
