### PR TITLE
Branch 2.5 upgrade to junit5

### PR DESCRIPTION
**Pull request by bcode2**
This PR...

Fixes issue #

## Changes
- Upgrade  to JUnit5. Test have not been checked if they are still necessary or valid as some of them are referring to very old issues. A second round for cleaning will be required

-----------------
## Checklist
- [x] tested locally
- [ ] updated the docs
- [ ] added appropriate test
- [x] signed-off on the DCO referenced in the CONTRIBUTING link below via `git commit -s` on my commits, and submit this code under terms of the Apache 2.0 license and assign copyright to the Quartz project owners
  (If you're not using command-line, you can use a [browser extension](https://github.com/scottrigby/dco-gh-ui) )
-----------------
In submitting this contribution, I agree to the terms of contributing as referred to here: 
https://github.com/quartz-scheduler/contributing/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by bcode2** [comment]
I get this results when running  the test
image

**Comment by bcode2** [comment]
@jhouserizer can you re-run the test please?

**Comment by jhouserizer** [comment]
Hmm.  That FlakyJdbcSchedulerTest is itself proving to be flaky in the CI environment the last couple of weeks.

**Review by jhouserizer — APPROVED** [review]
Very nice, thank you.

**Pull request merged**
